### ISSUE TITLE
Crash on file deletion (via executable)

### ISSUE THREAD

**Issue by AlexWayfer** [thomasfl/filewatcher#82]
Sometimes I've got something like this:

```
/home/alex/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/filewatcher-1.0.0/lib/filewatcher/env.rb:13:in `realpath': No such file or directory @ realpath_rec - /home/alex/Projects/some_project/some_file (Errno::ENOENT)
	from /home/alex/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/filewatcher-1.0.0/lib/filewatcher/env.rb:13:in `realpath'
	from /home/alex/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/filewatcher-1.0.0/lib/filewatcher/env.rb:13:in `initialize'
	from /home/alex/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/filewatcher-1.0.0/bin/filewatcher:91:in `new'
	from /home/alex/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/filewatcher-1.0.0/bin/filewatcher:91:in `block in <top (required)>'
	from /home/alex/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/filewatcher-1.0.0/lib/filewatcher/cycles.rb:40:in `block (2 levels) in trigger_changes'
	from /home/alex/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/filewatcher-1.0.0/lib/filewatcher/cycles.rb:39:in `each'
	from /home/alex/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/filewatcher-1.0.0/lib/filewatcher/cycles.rb:39:in `block in trigger_changes'
```

Also I saw this in some Travis CI jobs:

* https://travis-ci.org/thomasfl/filewatcher/jobs/296424479
* https://travis-ci.org/thomasfl/filewatcher/jobs/296432553
* One more on MRI 2.3 (was restarted, I can't find)

**Comment by thomasfl** [comment]
It’s so great to make filewatcher mor robust.
